CREATE TABLE IF NOT EXISTS public."Account"
(
    "AccountId" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    "AccountType" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    "AccountAmount" double precision NOT NULL,
    "AccountState" boolean NOT NULL,
    "ClientId" integer NOT NULL,
    CONSTRAINT "PK_Account" PRIMARY KEY ("AccountId")
)

CREATE TABLE IF NOT EXISTS public."Person"
(
    "PersonId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "PersonName" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "PersonDirection" character varying(150) COLLATE pg_catalog."default" NOT NULL,
    "PersonGender" character varying(15) COLLATE pg_catalog."default",
    "PersonAge" integer NOT NULL,
    "PersonDocumentId" character varying(10) COLLATE pg_catalog."default",
    "PersonPhone" character varying(15) COLLATE pg_catalog."default",
    CONSTRAINT "PK_Person" PRIMARY KEY ("PersonId")
)

CREATE TABLE IF NOT EXISTS public."Client"
(
    "ClientId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "ClientPassword" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    "ClientState" boolean NOT NULL,
    "PersonId" integer NOT NULL,
    CONSTRAINT "PK_Client" PRIMARY KEY ("ClientId"),
    CONSTRAINT "FK_Client_Person_PersonId" FOREIGN KEY ("PersonId")
        REFERENCES public."Person" ("PersonId") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

CREATE INDEX IF NOT EXISTS "IX_Client_PersonId"
    ON public."Client" USING btree
    ("PersonId" ASC NULLS LAST)
    TABLESPACE pg_default;

CREATE TABLE IF NOT EXISTS public."Movement"
(
    "MovementId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "MovementDate" timestamp with time zone NOT NULL,
    "MovementType" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    "MovementState" boolean NOT NULL,
    "MovementAmount" double precision NOT NULL,
    "MovementBalance" double precision NOT NULL,
    "AccountId" text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PK_Movement" PRIMARY KEY ("MovementId")
)
